name: voxcpm-env

options:
  buildTimeout: 3600

triggers:
  - type: push
    branch: main

jobs:
  build-image:
    runner: cnb-runner
    steps:
      - name: checkout code
        type: checkout
      - name: build voxcpm image
        type: docker-build
        params:
          image: docker.cnb.cool/shijian_yiqiang/voxcpm:v1.0
          dockerfile: ./Dockerfile
      - name: push image to registry
        type: docker-push
        params:
          image: docker.cnb.cool/shijian_yiqiang/voxcpm:v1.0

$:
  vscode:
    - docker:
        image:
          name: docker.cnb.cool/shijian_yiqiang/voxcpm:v1.0
          dockerUser: $CNB_TOKEN_USER_NAME
          dockerPassword: $CNB_TOKEN
      runner:
        cpus: 8
        memory: 32G
        tags: cnb:arch:amd64:gpu
      env:
        CNB_WELCOME_EXECUTE_COMMAND: bash /workspace/init.sh
      services:
        - vscode
        - docker
